import argparse
parser = argparse.ArgumentParser()
parser.add_argument("echo")
parser.add_argument("square", type=int)
parser.add_argument("--cube", default=2, type=int)
group = parser.add_mutually_exclusive_group()
group.add_argument("-v", "--verbose", action="store_true")
group.add_argument("-q", "--quiet", action="store_true")
args = parser.parse_args()
print(args.echo)
print(args.square**2)
print(args.cube**3)
print(args.verbose)
